# Generated by Django 4.2.15 on 2024-08-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='delivery_partners',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='staff',
        ),
    ]
