# Generated by Django 4.2.15 on 2024-08-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_delivery_partners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
