# Generated by Django 4.2.15 on 2024-08-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='images',
            field=models.CharField(blank=True, default=list, max_length=255, null=True),
        ),
    ]
