# Generated by Django 4.2.15 on 2024-08-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
        ),
    ]
