# Generated by Django 4.2.15 on 2024-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_remove_branch_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
